version: '2'
services:
    authserver-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/authserver/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=authserver
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
